name: flutter_zpl_generator
description: A comprehensive Flutter package for generating ZPL (Zebra Programming Language) labels with Labelary API integration and live preview capabilities.
version: 1.0.0
homepage: https://github.com/yourusername/flutter_zpl_generator
repository: https://github.com/yourusername/flutter_zpl_generator
issue_tracker: https://github.com/yourusername/flutter_zpl_generator/issues

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.2.0
  http: ^1.1.0
  hex: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

# This package does not require any Flutter-specific configuration
flutter:
  # This package contains widgets that can be used in Flutter apps
  uses-material-design: false

topics:
  - zpl
  - labels
  - printing
  - zebra
  - labelary
  - barcode
  - thermal-printing

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: